### PR TITLE
wrapper function added

### PR DESCRIPTION
**Pull request by bhbam**
The wrapper function was added to prevent initializing the configuration over and over and segmentation fault error solved

### CODE REVIEW

**Comment by dnoonan08** [comment]
@bhbam please also make the changes for the other classes in the `testing/utils` directory.  
https://github.com/bhbam/econt_sw/tree/master/econt_sw/testing/utils

All of these have the same issue (`uhal` loads the device in the initializer) so would potentially be subject to the same bug if they get called multiple times.

**Comment by dnoonan08** [comment]
@bhbam can you also please edit the description for the pull request, just to describe the problem it is trying to fix.  This will be useful in case we are trying to look back at the history and remember how we solved this

**Comment by dnoonan08** [comment]
@bhbam It looks like you made the pull request, but then pushed two commits that reverted all of your changes, so nothing is getting changed here.  Can you please reset to before the last two commits so that we can review the changes

**Comment by bhbam** [comment]
> @bhbam can you also please edit the description for the pull request, just to describe the problem it is trying to fix. This will be useful in case we are trying to look back at the history and remember how we solved this

Sorry I want to push the changes to new branch (not master) so I tried to revert the change. Now I am pushed to new branch and created pull request.

**Comment by dnoonan08** [comment]
Closing this pull request without merging.  It is superceded by #17

**Pull request closed without merging**
